### ISSUE TITLE
PicklingError

### ISSUE THREAD

**Issue by scholich** [cimatosa/jobmanager#1]
When run under windows with a fresh WinPython 3.3.5 installation the following error occurs.
The source of the problem is currently unclear.

```
C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\python.exe C:/Users/scholich/git/jobmanager/simple_example/simple_example.py
Example_Server (5312): I'm the JobManager_Server main process
Process Process-1:
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\process.py", line 95, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\scholich\git\jobmanager\simple_example\simple_example.py", line 43, in run_server
    server = Example_Server()
  File "C:\Users\scholich\git\jobmanager\simple_example\simple_example.py", line 27, in __init__
    verbose=2)
  File "C:\Users\scholich\git\jobmanager\jobmanager.py", line 282, in __init__
    self.__start_SyncManager()
  File "C:\Users\scholich\git\jobmanager\jobmanager.py", line 317, in __start_SyncManager
    self.manager.start(setup_SIG_handler_manager)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\managers.py", line 486, in start
    self._process.start()
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\process.py", line 111, in start
    self._popen = Popen(self)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\forking.py", line 248, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\forking.py", line 166, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'function'>: attribute lookup builtins.function failed
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\forking.py", line 351, in main
    self = load(from_parent)
EOFError
Process Process-2:
Traceback (most recent call last):
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\process.py", line 258, in _bootstrap
    self.run()
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\process.py", line 95, in run
    self._target(*self._args, **self._kwargs)
  File "C:\Users\scholich\git\jobmanager\simple_example\simple_example.py", line 51, in run_client
    client.start()
  File "C:\Users\scholich\git\jobmanager\jobmanager.py", line 929, in start
    p.start()
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\process.py", line 111, in start
    self._popen = Popen(self)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\forking.py", line 248, in __init__
    dump(process_obj, to_child, HIGHEST_PROTOCOL)
  File "C:\WinPython-64bit-3.3.5.0\python-3.3.5.amd64\lib\multiprocessing\forking.py", line 166, in dump
    ForkingPickler(file, protocol).dump(obj)
_pickle.PicklingError: Can't pickle <class 'function'>: attribute lookup builtins.function failed

Process finished with exit code 0
```

**Comment by cimatosa** [comment]
I think I might a hint for that problem. On Windows, sub processes are 'spawned' (see: https://docs.python.org/3.4/library/multiprocessing.html?highlight=process#contexts-and-start-methods), which means a 'The parent process starts a fresh python interpreter process'. In order to pass data to the sub process (which includes the functions to call) this data needs to be pickable, so the function must not be defined in local scope, roughly speaking) ...

I might take a look at that my self, at some time.

There should be a simple test on Linux for that by just setting the spawn method to 'spawn' rather than 'fork'.

Cheers Richard
